### ISSUE TITLE
configure check for yajl needs to check >= 2.1

### ISSUE THREAD

**Issue by bmenrigh** [farsightsec/nmsg#29]
If you try to compile nmsg against yajl 2.0.x (tested with 2.0.4) you will get a linking error with an undefined reference to yajl_gen_reset

The relevant configure.ac entry that needs to be updated is

    AC_ARG_WITH([yajl], AS_HELP_STRING([--without-yajl], [Disable yajl support]))
    if test "x$with_yajl" != "xno"; then
        PKG_CHECK_MODULES([yajl], [yajl >= 2])
        AC_DEFINE([HAVE_YAJL], [1], [Define to 1 if yajl support is enabled.])
        use_yajl="true"
    else
        use_yajl="false"
    fi

**Comment by edmonds** [comment]
Hi, Brandon:

Thanks for the build report! Do you mind mentioning what OS you're using, and whether you built yajl from source or used the version available from your OS vendor?

We could very easily update the pkg-config version check to `[yajl >= 2.1.0]`, but it looks like that version is not available in CentOS/RHEL 7 (not even in EPEL). It is available in Debian stable, though.

@hstern Any thoughts? Would it be better to replace the call to `yajl_gen_reset` with something equivalent that works on yajl 2.0.4, even if that happens to be a little bit more inefficient, if it would allow Red Hat users to avoid building yajl from source?

**Comment by bmenrigh** [comment]
Hi edmonds, I'm on a Gentoo machine:

    $ uname -a
    Linux lambda 4.2.2 #4 SMP PREEMPT Sat Dec 5 00:29:33 UTC 2015 x86_64 Intel(R) Core(TM) i7-4900MQ CPU @ 2.80GHz GenuineIntel GNU/Linux

    $ gcc --version
    gcc (Gentoo 4.9.3 p1.3, pie-0.6.3) 4.9.3
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I built yajl from source.  Actually I also built wdns and libxs from source too.  Instead of installing them system wide I pointed configure at their locations (to bypass pkg-config) via this mess:

    libwdns_LIBS="/home/brenrigh/download/farsight_wdns/wdns/wdns/libwdns.la" libwdns_CFLAGS="-I/home/brenrigh/download/farsight_wdns/wdns/wdns/" libxs_LIBS="/home/brenrigh/download/libxs/libxs/src/libxs.la" libxs_CFLAGS="-I/home/brenrigh/download/libxs/libxs/include/" yajl_LIBS="-L/home/brenrigh/download/libyajl/yajl/build/yajl-2.1.1/lib/ -lyajl" yajl_CFLAGS="-I/home/brenrigh/download/libyajl/yajl/build/yajl-2.1.1/include/yajl/ -I/home/brenrigh/download/libyajl/yajl/build/yajl-2.1.1/include/"  ./configure

**Comment by edmonds** [comment]
Oh, ha, somehow I was thinking you were using a more "enterprise-y" distro...

You might be able to avoid that long invocation to configure by installing the dependencies into their own tree (by setting e.g. `./configure --prefix=...` when building/installing the dependencies) and then setting `PKG_CONFIG_PATH=.../lib/pkgconfig` when running nmsg's ./configure. At least I think this should work, since most of our dependencies use pkg-config, other than zlib and libpcap.

**Comment by edmonds** [comment]
Though, that will cause the binaries to pick up RPATHs, which may not be what you want.

**Comment by hstern** [comment]
fixed in merge request #31
